
CREATE TABLE Contact (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
email VARCHAR(50),
phone INT(20),
message VARCHAR(100) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE emplyoee (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
branch VARCHAR(30) NOT NULL,
first_name VARCHAR(50),
second_name VARCHAR(50),
age INT(20),
specialty VARCHAR(100) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
